#
# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.
#
include(binutils.common)
include(FetchContent)


list(APPEND ESP32_Sources
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/Device_BlockStorage.c
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/nanoCRT.cpp
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/nanoHAL.cpp
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/nanoSupport_CRC32.c

            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/platform_heap.c
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/targetHAL.c
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/targetHAL_Rtos.c
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/targetHAL_StorageOperation.cpp
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/targetHAL_Time.cpp
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/targetPAL.c 
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/targetPAL_Events.cpp
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/targetPAL_Time.cpp
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/core/Target_BlockStorage_ESP32FlashDriver.c

            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/WireProtocol/WireProtocol_HAL_Interface.c
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/WireProtocol/WireProtocol_ReceiverThread.c

            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Configuration/platform_BlockStorage.c
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Configuration/target_BlockStorage.c
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Configuration/target_common.c
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Configuration/Memory.cpp

            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Startup/CLR_Startup_Thread.c
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Startup/targetHAL.cpp

            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/targetHAL_Power.c
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/targetRandom.cpp
)
list(APPEND ESP32_Includes
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/Core
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/FileSystem
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/Network
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/WireProtocol
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/common/include
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Configuration
            ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Startup
)
list(APPEND IDF_INCLUDES
            ${IDF_PATH}/components/bt/include
            ${IDF_PATH}/components/bt/common/include
            ${IDF_PATH}/components/bt/host/nimble/nimble/include
            ${IDF_PATH}/components/bt/host/nimble/nimble/nimble/controller/include
            ${IDF_PATH}/components/bt/host/nimble/nimble/nimble/host/include
            ${IDF_PATH}/components/bt/host/nimble/port/includeendif()
            ${IDF_PATH}/components/esp_adc/include
            ${IDF_PATH}/components/esp_adc/interface
            ${IDF_PATH}/components/esp_common/include
            ${IDF_PATH}/components/esp_driver_gpio/include
            ${IDF_PATH}/components/esp_driver_i2s/include
            ${IDF_PATH}/components/esp_driver_ledc/include
            ${IDF_PATH}/components/esp_driver_spi/include
            ${IDF_PATH}/components/esp_partition/include
            ${IDF_PATH}/components/esp_driver_uart/include
            ${IDF_PATH}/components/esp_system/include
            ${IDF_PATH}/components/freertos/config/include
            ${IDF_PATH}/components/freertos/config/riscv/include 
            ${IDF_PATH}/components/freertos/esp_additions/include
            ${IDF_PATH}/components/freertos/FreeRTOS-Kernel/include
            ${IDF_PATH}/components/hal/include
            ${IDF_PATH}/components/hal/esp32p4/include
            ${IDF_PATH}/components/heap/include
            ${IDF_PATH}/components/nvs_flash/include
            ${IDF_PATH}/components/partition_table/include
            ${IDF_PATH}/components/soc/include
            ${IDF_PATH}/components/soc/esp32p4/include
            ${IDF_PATH}/components/vfs/include
)
target_sources(nanoCLR PUBLIC ${ESP32_Sources} )
target_include_directories(nanoCLR PUBLIC
                           ${ESP32_Includes}
                           ${IDF_INCLUDES}
)

# Create a sdkconfig.custom file to override the default sdkconfig values
set(SDKCONFIG_OVERRIDES_FILE ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Configuration/sdkconfig.custom )
file(WRITE ${SDKCONFIG_OVERRIDES_FILE} "# Generated by CMake\n")

# ESP32P4_REVISION in the format of "VX.Y" where X is the major revision, Y is the minor revision
string(SUBSTRING "${ESP32P4_REVISION}" 1 1 REV_MAJOR)
if(REV_MAJOR GREATER_EQUAL 3)
    file(APPEND ${SDKCONFIG_OVERRIDES_FILE} "CONFIG_ESP32P4_REV_MIN=3\n")
    file(APPEND ${SDKCONFIG_OVERRIDES_FILE} "CONFIG_ESP32P4_SELECTS_REV_LESS_V3=n\n")
else()
    file(APPEND ${SDKCONFIG_OVERRIDES_FILE} "CONFIG_ESP32P4_REV_MIN=1\n")
    file(APPEND ${SDKCONFIG_OVERRIDES_FILE} "CONFIG_ESP32P4_SELECTS_REV_LESS_V3=y\n")
endif()

if(PSRAM)
    file(APPEND ${SDKCONFIG_OVERRIDES_FILE} "CONFIG_SPIRAM=y\n")
    file(APPEND ${SDKCONFIG_OVERRIDES_FILE} "CONFIG_SPIRAM_MODE_OCT=y\n")
    file(APPEND ${SDKCONFIG_OVERRIDES_FILE} "CONFIG_SPIRAM_SPEED_200M=y\n")
endif()

# Create a list of IDF components to add to the build based on the options selected in the CMakeLists.txt file
set( ADDITIONAL_IDF_COMPONENTS
      freertos
      esp_driver_uart
      esp_timer
      esp_event
      nvs_flash
      vfs
)

if(CONFIG_SUPPORT_COREIO)
    # Components to add to the build for COREIO support, ledc quite often used for PWM, so we add it here as well
    list(APPEND ADDITIONAL_IDF_COMPONENTS
                esp_driver_adc
                esp_driver_gpio
                esp_driver_i2c
                esp_driver_i2s
                esp_driver_ledc
                esp_driver_spi
    )
endif()

if(CONFIG_SUPPORT_BLUETOOTH)
    list(APPEND ADDITIONAL_IDF_COMPONENTS
                bt
    )
endif()

if(CONFIG_SUPPORT_GRAPHICS)
    list(APPEND ADDITIONAL_IDF_COMPONENTS
                esp_lcd
                esp_driver_ppa
    )
endif()

if(CONFIG_SUPPORT_THREAD)
    list(APPEND ADDITIONAL_IDF_COMPONENTS
                openthread
    )
endif()


if(CONFIG_SUPPORT_FILESYSTEM)
    list(APPEND ADDITIONAL_IDF_COMPONENTS
                littlefs
                fatfs
    )
endif()

if(CONFIG_SUPPORT_USBSTREAM)
    list(APPEND ADDITIONAL_IDF_COMPONENTS
                tinyusb
                esp_tinyusb
    )
endif()



if(CONFIG_SUPPORT_WIFI)
    list(APPEND ADDITIONAL_IDF_COMPONENTS
                esp_hosted
                esp_wifi_remote
                esp_wifi
                esp_netif
                esp_event
                lwip
    )
endif()

# Let the IDF build system handle the build of the IDF core and components used by nanoCLR
include(${ESP32_IDF_PATH}/tools/cmake/idf.cmake)
idf_build_process(esp32p4
                  COMPONENTS 
                     ${ADDITIONAL_IDF_COMPONENTS}
                  SDKCONFIG_DEFAULTS
                    ${SDKCONFIG_OVERRIDES_FILE}
                  PROJECT_NAME
                     "nanoCLR"
                  PROJECT_VER
                       ${BUILD_VERSION}
                  PROJECT_DIR
                       ${CMAKE_SOURCE_DIR}

)
foreach(component ${ADDITIONAL_IDF_COMPONENTS})
     list(APPEND IDF_LIBRARIES_TO_ADD
                 idf::${component}
     )
endforeach()
target_link_libraries(nanoCLR ${IDF_LIBRARIES_TO_ADD})
target_link_options(nanoCLR PUBLIC "-Wl,--no-warn-rwx-segments")
idf_build_executable(nanoCLR)

# Configuration
configure_file(${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Configuration/target_os.h.in       ${CMAKE_BINARY_DIR}/target_os.h @ONLY)
configure_file(${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Configuration/target_platform.h.in ${CMAKE_BINARY_DIR}/target_platform.h @ONLY)
configure_file(${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Configuration/target_common.h.in   ${CMAKE_BINARY_DIR}/target_common.h @ONLY)
configure_file(${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Configuration/target_board.h.in    ${CMAKE_BINARY_DIR}/target_board.h @ONLY)

add_custom_target(generate_partition ALL
                  COMMAND
                  "python"
                  ${ESP32_IDF_PATH}/components/partition_table/gen_esp32part.py 
                  --flash-size  ${PARTITION_SIZE} 
                  ${CMAKE_SOURCE_DIR}/targets/${VENDOR}/${TARGET_SERIES}/Configuration/partition_${PARTITION_SIZE}.csv
                  ${CMAKE_BINARY_DIR}/partitions_${PARTITION_SIZE}.bin
                  COMMENT
                  "Generate selected partition table size of  flash"
)

#   # if needed, "fix" the reported version so it doesn't show '-dirty'
#   # this is because we could be deleting some files and tweaking others in the IDF
#
#   get_property(MY_IDF_VER TARGET __idf_build_target PROPERTY IDF_VER)
#   string(FIND ${MY_IDF_VER} "-dirty" MY_IDF_VER_DIRTY)
#   if(${MY_IDF_VER_DIRTY} GREATER -1)
#
#       # found '-dirty' in the version string
#       string(REPLACE "-dirty" "" MY_IDF_VER_FIXED "${MY_IDF_VER}")
#       set_property(TARGET __idf_build_target PROPERTY IDF_VER ${MY_IDF_VER_FIXED})
#       set(IDF_VER_FIXED ${MY_IDF_VER_FIXED} CACHE INTERNAL "IDF version as CMake var")
#
#       # for COMPILE DEFINITIONS it's a bit more work
#       get_property(IDF_COMPILE_DEFINITIONS TARGET __idf_build_target PROPERTY COMPILE_DEFINITIONS )
#
#       string(REPLACE "-dirty" "" IDF_COMPILE_DEFINITIONS_FIXED "${IDF_COMPILE_DEFINITIONS}")
#       set_property(TARGET __idf_build_target PROPERTY COMPILE_DEFINITIONS ${IDF_COMPILE_DEFINITIONS_FIXED})
#       
#       message(STATUS "Fixed IDF version. Is now: ${MY_IDF_VER_FIXED}")
#   endif()
