#include "nanoFramework_NativeIO.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeAdc::Read___STATIC__I4__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeDac::Write___STATIC__VOID__I4__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeGpio::ConfigurePin___STATIC__VOID__I4__nanoFrameworkNativeIOGpioPinMode__nanoFrameworkNativeIOGpioBias,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeGpio::Read___STATIC__nanoFrameworkNativeIOGpioPinLevel__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeGpio::Write___STATIC__VOID__I4__nanoFrameworkNativeIOGpioPinLevel,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeGpio::AddInterrupt___STATIC__VOID__I4__nanoFrameworkNativeIOGpioInterruptMode,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeGpio::EnableInterrupt___STATIC__VOID__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeGpio::DisableInterrupt___STATIC__VOID__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeGpio::RemoveInterrupt___STATIC__VOID__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeI2C::Open___STATIC__BOOLEAN__I4__I4__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeI2C::AddSlaveDevice___STATIC__BOOLEAN__I4__nanoFrameworkNativeIOBusSpeed__U2,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeI2C::Probe___STATIC__BOOLEAN__I4__U2__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeI2C::Write___STATIC__BOOLEAN__I4__U2__SZARRAY_U1__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeI2C::Read___STATIC__BOOLEAN__I4__U2__SZARRAY_U1__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeI2C::WriteRead___STATIC__BOOLEAN__I4__U2__SZARRAY_U1__I4__SZARRAY_U1__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativePwm::Initialize___STATIC__VOID__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativePwm::ConfigurePin___STATIC__VOID__I4__I4__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativePwm::SetDutyCycle___STATIC__VOID__I4__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativePwm::SetFrequency___STATIC__VOID__I4__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativePwm::Start___STATIC__VOID__I4__I4,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativePwm::Stop___STATIC__VOID__I4__BOOLEAN,
    Library_nanoFramework_NativeIO_nanoFramework_NativeIO_NativeTouch::Read___STATIC__I4__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_NativeIO =
{
    "nanoFramework.NativeIO",
    0x76C62C19,
    method_lookup,
    { 100, 1, 0, 6 }
};

// clang-format on
