//
// Copyright (c) .NET Foundation and Contributors
// See LICENSE file in the project root for full license information.
//

//////////////////////////////////////////////////////////////////////////////
// This file was automatically generated by a tool.                         //
// Any changes you make here will be overwritten when it's generated again. //
//////////////////////////////////////////////////////////////////////////////

#ifndef TARGET_OS_H
#define TARGET_OS_H

#define VERSION_MAJOR    0U
#define VERSION_MINOR    0U
#define VERSION_BUILD    0U
#define VERSION_REVISION 0U

#define TARGETINFOSTRING "Debug build, chip rev. >= 1, support for PSRAM, support for BLE"

#define IDF_VER_FIXED    "v5.4.4"

#include "nf_config.h"

/* #undef NANOCLR_PROFILE_NEW_CALLS */
/* #undef NANOCLR_PROFILE_NEW_ALLOCATIONS */
/* #undef NANOCLR_TRACE_MEMORY_STATS */

#endif // TARGET_OS_H
