#
# Copyright (c .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.
#

include(FetchContent)

include(binutils.ESP32)

list(APPEND ESP32_IDF_INCLUDE_DIRS
            ${CMAKE_BINARY_DIR}/config
            ${IDF_PATH_CMAKED}/components/driver/deprecated
            ${IDF_PATH_CMAKED}/components/driver/esp32p4/include
            ${IDF_PATH_CMAKED}/components/driver/esp32p4/include/driver
            ${IDF_PATH_CMAKED}/components/driver/i2c/include
            ${IDF_PATH_CMAKED}/components/esp_adc/esp32p4/include
            ${IDF_PATH_CMAKED}/components/esp_adc/include
            ${IDF_PATH_CMAKED}/components/esp_common/include
            ${IDF_PATH_CMAKED}/components/esp_driver_dac/include
            ${IDF_PATH_CMAKED}/components/esp_driver_gpio/include
            ${IDF_PATH_CMAKED}/components/esp_driver_gptimer/include
            ${IDF_PATH_CMAKED}/components/esp_driver_i2c/include
            ${IDF_PATH_CMAKED}/components/esp_driver_i2s/include
            ${IDF_PATH_CMAKED}/components/esp_driver_ledc/include
            ${IDF_PATH_CMAKED}/components/esp_driver_parlio/include
            ${IDF_PATH_CMAKED}/components/esp_driver_pcnt/include
            ${IDF_PATH_CMAKED}/components/esp_driver_ppa/include
            ${IDF_PATH_CMAKED}/components/esp_driver_sdmmc/include
            ${IDF_PATH_CMAKED}/components/esp_driver_sdspi/include
            ${IDF_PATH_CMAKED}/components/esp_driver_spi/include
            ${IDF_PATH_CMAKED}/components/esp_driver_uart/include
            ${IDF_PATH_CMAKED}/components/esp_driver_usb_serial_jtag/include
            ${IDF_PATH_CMAKED}/components/esp_eth/include
            ${IDF_PATH_CMAKED}/components/esp_event/include
            ${IDF_PATH_CMAKED}/components/esp_hw_support/dma/include
            ${IDF_PATH_CMAKED}/components/esp_hw_support/include
            ${IDF_PATH_CMAKED}/components/esp_hw_support/include
            ${IDF_PATH_CMAKED}/components/esp_hw_support/include/soc
            ${IDF_PATH_CMAKED}/components/esp_hw_support/ldo/include
            ${IDF_PATH_CMAKED}/components/esp_lcd/dsi
            ${IDF_PATH_CMAKED}/components/esp_lcd/dsi/include
            ${IDF_PATH_CMAKED}/components/esp_lcd/include
            ${IDF_PATH_CMAKED}/components/esp_lcd/interface
            ${IDF_PATH_CMAKED}/components/esp_lcd/priv_include
            ${IDF_PATH_CMAKED}/components/esp_netif/include
            ${IDF_PATH_CMAKED}/components/esp_netif/lwip
            ${IDF_PATH_CMAKED}/components/esp_partition/include
            ${IDF_PATH_CMAKED}/components/esp_pm/include
            ${IDF_PATH_CMAKED}/components/esp_ringbuf/include
            ${IDF_PATH_CMAKED}/components/esp_rom/esp32p4
            ${IDF_PATH_CMAKED}/components/esp_rom/esp32p4/include
            ${IDF_PATH_CMAKED}/components/esp_rom/esp32p4/include/esp32p4
            ${IDF_PATH_CMAKED}/components/esp_rom/esp32p4/include/esp32p4/rom
            ${IDF_PATH_CMAKED}/components/esp_rom/include
            ${IDF_PATH_CMAKED}/components/esp_system/include
            ${IDF_PATH_CMAKED}/components/esp_timer/include
            ${IDF_PATH_CMAKED}/components/esp_wifi/include
            ${IDF_PATH_CMAKED}/components/esp_wifi/include/local
            ${IDF_PATH_CMAKED}/components/fatfs/diskio
            ${IDF_PATH_CMAKED}/components/fatfs/src
            ${IDF_PATH_CMAKED}/components/fatfs/vfs
            ${IDF_PATH_CMAKED}/components/freertos/config/include
            ${IDF_PATH_CMAKED}/components/freertos/config/include/freertos
            ${IDF_PATH_CMAKED}/components/freertos/config/riscv/include
            ${IDF_PATH_CMAKED}/components/freertos/esp_additions/arch/riscv/include
            ${IDF_PATH_CMAKED}/components/freertos/esp_additions/include
            ${IDF_PATH_CMAKED}/components/freertos/esp_additions/include/freertos
            ${IDF_PATH_CMAKED}/components/freertos/FreeRTOS-Kernel/include
            ${IDF_PATH_CMAKED}/components/freertos/FreeRTOS-Kernel/portable/riscv/include
            ${IDF_PATH_CMAKED}/components/freertos/FreeRTOS-Kernel/portable/riscv/include/freertos
            ${IDF_PATH_CMAKED}/components/hal/esp32p4/include
            ${IDF_PATH_CMAKED}/components/hal/include
            ${IDF_PATH_CMAKED}/components/hal/include
            ${IDF_PATH_CMAKED}/components/hal/platform_port/include
            ${IDF_PATH_CMAKED}/components/heap
            ${IDF_PATH_CMAKED}/components/heap/include
            ${IDF_PATH_CMAKED}/components/log/include
            ${IDF_PATH_CMAKED}/components/lwip/include
            ${IDF_PATH_CMAKED}/components/lwip/include/apps
            ${IDF_PATH_CMAKED}/components/lwip/lwip/src/include
            ${IDF_PATH_CMAKED}/components/lwip/lwip/src/include/lwip
            ${IDF_PATH_CMAKED}/components/lwip/port/esp32xx/include
            ${IDF_PATH_CMAKED}/components/lwip/port/freertos/include
            ${IDF_PATH_CMAKED}/components/lwip/port/include
            ${IDF_PATH_CMAKED}/components/mbedtls/mbedtls/include
            ${IDF_PATH_CMAKED}/components/mbedtls/port/include
            ${IDF_PATH_CMAKED}/components/newlib/platform_include
            ${IDF_PATH_CMAKED}/components/nvs_flash/include
            ${IDF_PATH_CMAKED}/components/riscv/esp32p4/include
            ${IDF_PATH_CMAKED}/components/riscv/include
            ${IDF_PATH_CMAKED}/components/sdmmc/include
            ${IDF_PATH_CMAKED}/components/soc/esp32p4/include
            ${IDF_PATH_CMAKED}/components/soc/esp32p4/include/soc
            ${IDF_PATH_CMAKED}/components/soc/esp32p4/register
            ${IDF_PATH_CMAKED}/components/soc/esp32p4/register/hw_ver3
            ${IDF_PATH_CMAKED}/components/soc/include
            ${IDF_PATH_CMAKED}/components/spi_flash/include
            ${IDF_PATH_CMAKED}/components/spiffs/include
            ${IDF_PATH_CMAKED}/components/vfs/include
            ${IDF_PATH_CMAKED}/components/wear_levelling/include
            ${IDF_PATH_CMAKED}/components/wpa_supplicant/include/esp_supplicant
)

include(ESP32_P4_GCC_options)
